@startuml
'https://plantuml.com/class-diagram

class Cliente{
    -rut: String
    -nombre: String
    -apellidoPaterno: String
    -apellidoMaterno: String
    -nombreUsuario: String
    -contrasenia: String
    -categoriaSocio: String
    +Cliente(rut: String, nombre: String, apellidoPaterno: String, apellidoMaterno: String,
    nombreUsuario: String, contrasenia: String, categoriaSocio: String)
    +get's()
    +set's()
}

class ContenedorClientes{
    -listaClientes: Cliente[]
    -cantMax: int
    -cantActual: int
    +ContenedorClientes(cantMax: int)
    +agregarCliente(cliente: Cliente): boolean
    +buscarCliente(rut: String): int
    +obtenerCliente(posicion: int): Cliente
}

ContenedorClientes"1"o-->"*"Cliente

class Mesa{
    -id: int
    -tipoJuego: String
    -descripcion: String
    -apuestaMin: int
    -apuestaMax: int
    -estado: boolean
    +Mesa(id: int, tipoJuego: String, descripcion: String, apuestaMin: int,
    apuestaMax: int, estado: boolean)
    +get's()
    +set's()
}

class ContenedorMesas{
    -listaMesas: Mesa[]
    -cantMax: int
    -cantActual: int
    +ContenedorMesa(cantMax: int)
    +agregarMesa(mesa: Mesa): boolean
    +buscarMesa(id: int): int
    +obtenerMesa(posicion: int): Mesa
    }
ContenedorMesas"1"o-->"*"Mesa

class Jugada{
    -fechaJugada: String
    -apuesta: int
    -resultado: String
    -cliente: Cliente
    -mesa: Mesa
    +Jugada(fechaJugada: String, apuesta: int: resultado: String)
    +get's()
    +set's()
}

class ContenedorJugadas{
    -listaJugadas: Jugada[]
    -cantMax: int
    -cantActual: int
    +ContenedorJugadas(cantMax: int)
    +agregarJugada(jugada: Jugada): boolean
    +buscarJugada(rut: String): int
    +obtenerJugada(posicion: int): Jugada
}
ContenedorJugadas"1"--->"*"Jugada: tiene

class SistemaCasinoImpl{
    -listadoClientes: ContenedorClientes
    +SistemaCasinoImpl()
}

SistemaCasinoImpl"1"--->"1"ContenedorClientes: posee
SistemaCasinoImpl"1"--->"1"ContenedorMesas: posee
SistemaCasinoImpl"1"--->"1"SistemaCasino: implementa
SistemaCasinoImpl"1"--->"1"ContenedorJugadas: posee

interface SistemaCasino{
    +IniciarSesion(nombreUsuario: String, contrasenia: String): void
    +RegistrarUsuario(nombre: String, apellidoPaterno: String, apellidoMaterno: String,
    rut: String, nombreUsuario: String)
    +Salir(): void
    +RegistrarSesion(): void
    +MostrarHistorial(): void
    +GestionarCuenta(): void
    +VerDatos(): void
    +CambiarDeCategoria(opcion: String): void
    +CambiarContraseña(contraseniaActual: String, contraseniaNueva): void
    +Volver(): void
    +VerMesasDisponibles(): String
    +AdministrarMesas(): void
    +MostrarEstadistica(): String
    +CerrarSesion(): void
}
@enduml